/**
 * Mock data for development/demo — replace with Supabase queries once DB is live.
 * Field names match the actual DB schema (database.types.ts).
 */

import type { Guide, Experience, ExperienceImage } from '@/types'

type MockGuide = Guide & { experience_count: number }

export const MOCK_GUIDES: MockGuide[] = [
  {
    id: 'guide-1',
    user_id: 'user-1',
    full_name: 'Erik Bjørnsson',
    bio: 'Born and raised in the fjords of Western Norway, I have been guiding fishing expeditions for over 15 years. Specializing in Atlantic salmon and sea trout, I know every secret pool and hidden run in the region.',
    avatar_url: 'https://images.unsplash.com/photo-1553267751-1c148a7280a1?w=200&h=200&fit=crop&crop=face',
    cover_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop',
    country: 'Norway',
    city: 'Bergen',
    languages: ['English', 'Norwegian', 'German'],
    years_experience: 15,
    fish_expertise: ['Salmon', 'Sea Trout', 'Arctic Char'],
    certifications: 'Norwegian Fishing Guide License',
    instagram_url: 'https://instagram.com/erik_fjord_fishing',
    youtube_url: null,
    status: 'active',
    pricing_model: 'commission',
    stripe_account_id: 'acct_demo1',
    stripe_charges_enabled: true,
    stripe_payouts_enabled: true,
    verified_at: '2023-01-20T00:00:00Z',
    average_rating: 4.9,
    total_reviews: 87,
    created_at: '2023-01-15T00:00:00Z',
    updated_at: '2023-01-15T00:00:00Z',
    experience_count: 4,
  },
  {
    id: 'guide-2',
    user_id: 'user-2',
    full_name: 'Lars Magnusson',
    bio: 'Swedish fly fishing champion and guide with a passion for wild trout streams. I lead guests through the pristine wilderness of Northern Sweden, targeting brown trout and grayling in crystal-clear rivers.',
    avatar_url: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=200&h=200&fit=crop&crop=face',
    cover_url: 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=800&h=400&fit=crop',
    country: 'Sweden',
    city: 'Åre',
    languages: ['English', 'Swedish', 'Polish'],
    years_experience: 10,
    fish_expertise: ['Brown Trout', 'Grayling', 'Pike'],
    certifications: 'Swedish Sports Fishing Guide',
    instagram_url: 'https://instagram.com/lars_fly_fishing',
    youtube_url: 'https://youtube.com/@LarsFlyFishing',
    status: 'active',
    pricing_model: 'flat_fee',
    stripe_account_id: 'acct_demo2',
    stripe_charges_enabled: true,
    stripe_payouts_enabled: true,
    verified_at: '2023-03-25T00:00:00Z',
    average_rating: 4.8,
    total_reviews: 54,
    created_at: '2023-03-20T00:00:00Z',
    updated_at: '2023-03-20T00:00:00Z',
    experience_count: 3,
  },
  {
    id: 'guide-3',
    user_id: 'user-3',
    full_name: 'Matti Virtanen',
    bio: 'Finnish ice fishing expert and summer pike guide. My home waters in Finnish Lapland offer some of the most pristine fishing in Europe, with massive pike and perch hiding in our ancient lakes.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    cover_url: 'https://images.unsplash.com/photo-1551244072-5d12893278bc?w=800&h=400&fit=crop',
    country: 'Finland',
    city: 'Rovaniemi',
    languages: ['English', 'Finnish', 'Russian'],
    years_experience: 8,
    fish_expertise: ['Pike', 'Perch', 'Zander'],
    certifications: null,
    instagram_url: 'https://instagram.com/matti_lapland_fishing',
    youtube_url: null,
    status: 'active',
    pricing_model: 'commission',
    stripe_account_id: 'acct_demo3',
    stripe_charges_enabled: true,
    stripe_payouts_enabled: true,
    verified_at: '2023-06-15T00:00:00Z',
    average_rating: 4.7,
    total_reviews: 41,
    created_at: '2023-06-10T00:00:00Z',
    updated_at: '2023-06-10T00:00:00Z',
    experience_count: 2,
  },
]

type MockExperienceImage = ExperienceImage

type MockExperience = Experience & {
  guide: Pick<Guide, 'id' | 'full_name' | 'avatar_url' | 'country' | 'city' | 'average_rating'>
  images: MockExperienceImage[]
}

const makeImage = (
  id: string,
  experienceId: string,
  url: string,
  isCover = true,
  sortOrder = 0,
): MockExperienceImage => ({
  id,
  experience_id: experienceId,
  url,
  sort_order: sortOrder,
  is_cover: isCover,
  created_at: '2023-01-20T00:00:00Z',
})

const guideSnippet = (g: MockGuide) =>
  ({
    id: g.id,
    full_name: g.full_name,
    avatar_url: g.avatar_url,
    country: g.country,
    city: g.city,
    average_rating: g.average_rating,
  }) as Pick<Guide, 'id' | 'full_name' | 'avatar_url' | 'country' | 'city' | 'average_rating'>

export const MOCK_EXPERIENCES: MockExperience[] = [
  {
    id: 'exp-1',
    guide_id: 'guide-1',
    guide: guideSnippet(MOCK_GUIDES[0]),
    title: 'Atlantic Salmon Fly Fishing in Hardangerfjord',
    description:
      "Experience world-class Atlantic salmon fly fishing in one of Norway's most spectacular fjords. We'll target fresh-run fish using traditional Norwegian techniques in pristine, uncrowded waters.",
    fish_types: ['Salmon', 'Sea Trout'],
    duration_hours: 8,
    duration_days: null,
    max_guests: 2,
    price_per_person_eur: 450,
    difficulty: 'intermediate',
    what_included: [
      'All fishing equipment',
      'Fishing license',
      'Lunch',
      'Waders and boots',
      'Transfer from Bergen',
    ],
    what_excluded: ['Accommodation', 'Dinner', 'Personal travel insurance'],
    meeting_point: 'Bergen Harbor, Bryggen',
    location_city: 'Hardangerfjord',
    location_country: 'Norway',
    technique: 'Fly fishing',
    best_months: ['June', 'July', 'August'],
    catch_and_release: true,
    location_lat: 60.46,
    location_lng: 6.44,
    published: true,
    created_at: '2023-01-20T00:00:00Z',
    updated_at: '2023-01-20T00:00:00Z',
    images: [
      makeImage('img-1', 'exp-1', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-1b', 'exp-1', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', false, 1),
      makeImage('img-1c', 'exp-1', 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&h=600&fit=crop', false, 2),
      makeImage('img-1d', 'exp-1', 'https://images.unsplash.com/photo-1533601017-39c57d07fe0f?w=800&h=600&fit=crop', false, 3),
      makeImage('img-1e', 'exp-1', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', false, 4),
    ],
  },
  {
    id: 'exp-2',
    guide_id: 'guide-1',
    guide: guideSnippet(MOCK_GUIDES[0]),
    title: 'Full-Day Sea Trout Fishing — Fjord & River',
    description:
      'A comprehensive sea trout experience combining fjord fishing in the morning with river fishing in the afternoon. Perfect for anglers looking to maximize their chances on these elusive fish.',
    fish_types: ['Sea Trout', 'Brown Trout'],
    duration_hours: 10,
    duration_days: null,
    max_guests: 3,
    price_per_person_eur: 380,
    difficulty: 'beginner',
    what_included: [
      'Rod, reel, and flies provided',
      'Fishing license',
      'Coffee and snacks',
      'Waders',
    ],
    what_excluded: ['Accommodation', 'Meals (except snacks)'],
    meeting_point: 'Voss Train Station',
    location_city: 'Vossevangen',
    location_country: 'Norway',
    technique: 'Fly fishing',
    best_months: ['August', 'September', 'October'],
    catch_and_release: true,
    location_lat: 60.63,
    location_lng: 6.42,
    published: true,
    created_at: '2023-01-25T00:00:00Z',
    updated_at: '2023-01-25T00:00:00Z',
    images: [
      makeImage('img-2', 'exp-2', 'https://images.unsplash.com/photo-1585011664466-b7bbe92f34ef?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-2b', 'exp-2', 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop', false, 1),
      makeImage('img-2c', 'exp-2', 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&h=600&fit=crop', false, 2),
      makeImage('img-2d', 'exp-2', 'https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?w=800&h=600&fit=crop', false, 3),
      makeImage('img-2e', 'exp-2', 'https://images.unsplash.com/photo-1524422765977-c59e0a2fa4db?w=800&h=600&fit=crop', false, 4),
    ],
  },
  {
    id: 'exp-3',
    guide_id: 'guide-2',
    guide: guideSnippet(MOCK_GUIDES[1]),
    title: 'Wild Brown Trout Fly Fishing in the Swedish Mountains',
    description:
      'Chase wild brown trout through pristine mountain streams in the heart of Sweden. Lars will teach you the art of reading water and presenting dry flies in this spectacular wilderness setting.',
    fish_types: ['Brown Trout', 'Grayling'],
    duration_hours: 7,
    duration_days: null,
    max_guests: 2,
    price_per_person_eur: 320,
    difficulty: 'intermediate',
    what_included: [
      'Fly fishing instruction',
      'All tackle',
      'Fishing license',
      'Lunch by the stream',
    ],
    what_excluded: ['Accommodation', 'Transportation to meeting point'],
    meeting_point: 'Åre Village Center',
    location_city: 'Jämtland',
    location_country: 'Sweden',
    technique: 'Fly fishing',
    best_months: ['June', 'July', 'August'],
    catch_and_release: true,
    location_lat: 63.10,
    location_lng: 14.60,
    published: true,
    created_at: '2023-04-01T00:00:00Z',
    updated_at: '2023-04-01T00:00:00Z',
    images: [
      makeImage('img-3', 'exp-3', 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-3b', 'exp-3', 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=800&h=600&fit=crop', false, 1),
      makeImage('img-3c', 'exp-3', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop', false, 2),
      makeImage('img-3d', 'exp-3', 'https://images.unsplash.com/photo-1504173010664-32509107de4f?w=800&h=600&fit=crop', false, 3),
      makeImage('img-3e', 'exp-3', 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&h=600&fit=crop', false, 4),
    ],
  },
  {
    id: 'exp-4',
    guide_id: 'guide-2',
    guide: guideSnippet(MOCK_GUIDES[1]),
    title: 'Epic Pike Fishing — Swedish Lake Wilderness',
    description:
      'Target trophy pike in remote Swedish lakes accessible only by boat. These predators lurk in the lily pads and weed beds, ready to smash big lures thrown by experienced guides.',
    fish_types: ['Pike', 'Perch'],
    duration_hours: 8,
    duration_days: null,
    max_guests: 3,
    price_per_person_eur: 280,
    difficulty: 'beginner',
    what_included: [
      'Boat and fuel',
      'All lures and tackle',
      'Fishing license',
      'Lunch',
      'Fish cleaning',
    ],
    what_excluded: ['Accommodation'],
    meeting_point: 'Östersund Marina',
    location_city: 'Östersund',
    location_country: 'Sweden',
    technique: 'Lure fishing',
    best_months: ['May', 'June', 'September', 'October'],
    catch_and_release: false,
    location_lat: 63.18,
    location_lng: 14.64,
    published: true,
    created_at: '2023-04-15T00:00:00Z',
    updated_at: '2023-04-15T00:00:00Z',
    images: [
      makeImage('img-4', 'exp-4', 'https://images.unsplash.com/photo-1504173010664-32509107de4f?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-4b', 'exp-4', 'https://images.unsplash.com/photo-1531177071211-ed1b7991958a?w=800&h=600&fit=crop', false, 1),
      makeImage('img-4c', 'exp-4', 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&h=600&fit=crop', false, 2),
      makeImage('img-4d', 'exp-4', 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop', false, 3),
      makeImage('img-4e', 'exp-4', 'https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?w=800&h=600&fit=crop', false, 4),
    ],
  },
  {
    id: 'exp-5',
    guide_id: 'guide-3',
    guide: guideSnippet(MOCK_GUIDES[2]),
    title: 'Midnight Sun Pike Fishing in Finnish Lapland',
    description:
      'Fish under the magical midnight sun in the pristine lakes of Finnish Lapland. Pike reach trophy sizes here, and the scenery — birch forests, calm lakes, endless summer light — is unforgettable.',
    fish_types: ['Pike', 'Perch', 'Zander'],
    duration_hours: 6,
    duration_days: null,
    max_guests: 4,
    price_per_person_eur: 240,
    difficulty: 'beginner',
    what_included: [
      'Boat and equipment',
      'Fishing license',
      'Finnish sauna access',
      'Coffee and pastries',
    ],
    what_excluded: ['Accommodation', 'Meals'],
    meeting_point: 'Rovaniemi Harbor',
    location_city: 'Kemijärvi',
    location_country: 'Finland',
    technique: 'Lure fishing',
    best_months: ['June', 'July'],
    catch_and_release: false,
    location_lat: 66.71,
    location_lng: 27.43,
    published: true,
    created_at: '2023-07-01T00:00:00Z',
    updated_at: '2023-07-01T00:00:00Z',
    images: [
      makeImage('img-5', 'exp-5', 'https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-5b', 'exp-5', 'https://images.unsplash.com/photo-1551244072-5d12893278bc?w=800&h=600&fit=crop', false, 1),
      makeImage('img-5c', 'exp-5', 'https://images.unsplash.com/photo-1524422765977-c59e0a2fa4db?w=800&h=600&fit=crop', false, 2),
      makeImage('img-5d', 'exp-5', 'https://images.unsplash.com/photo-1585011664466-b7bbe92f34ef?w=800&h=600&fit=crop', false, 3),
      makeImage('img-5e', 'exp-5', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', false, 4),
    ],
  },
  {
    id: 'exp-6',
    guide_id: 'guide-1',
    guide: guideSnippet(MOCK_GUIDES[0]),
    title: '2-Day Salmon Expedition — Remote Norwegian River',
    description:
      "A premium 2-day salmon fishing expedition to a private stretch of one of Norway's finest rivers. Includes overnight stay in a traditional fishing cabin. Limited to just 2 anglers for a truly exclusive experience.",
    fish_types: ['Salmon', 'Arctic Char'],
    duration_hours: null,
    duration_days: 2,
    max_guests: 2,
    price_per_person_eur: 950,
    difficulty: 'expert',
    what_included: [
      '2 days guided fishing',
      'Overnight in cabin',
      'All meals',
      'All equipment',
      'Helicopter transfer',
    ],
    what_excluded: ['Travel to Bergen', 'Personal gear'],
    meeting_point: 'Bergen Airport',
    location_city: 'Sognefjord',
    location_country: 'Norway',
    technique: 'Fly fishing',
    best_months: ['July', 'August'],
    catch_and_release: true,
    location_lat: 61.22,
    location_lng: 7.00,
    published: true,
    created_at: '2023-02-10T00:00:00Z',
    updated_at: '2023-02-10T00:00:00Z',
    images: [
      makeImage('img-6', 'exp-6', 'https://images.unsplash.com/photo-1531177071211-ed1b7991958a?w=1200&h=900&fit=crop', true, 0),
      makeImage('img-6b', 'exp-6', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop', false, 1),
      makeImage('img-6c', 'exp-6', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', false, 2),
      makeImage('img-6d', 'exp-6', 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&h=600&fit=crop', false, 3),
      makeImage('img-6e', 'exp-6', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', false, 4),
    ],
  },
]
